dataset: transactions
source_system: txn_stream
raw_to_silver:
  transactio_1: transaction_id
  account_i: account_id
  transactio_2: transaction_date
  transactio_3: transaction_type
  amount: amount
  merchant: merchant_name
  category: category
  city: city
  country: country
date_format_raw: dd-MM-yy
notes: columns with similar prefixes will be referenced by position in Silver parsing