dataset: transactions
rules:
  - name: transaction_id_not_null
    type: completeness
    column: transaction_id
  - name: transaction_type_enum
    type: domain
    column: transaction_type
    allowed: ["Debit","Credit"]
  - name: amount_non_negative
    type: range
    column: amount
    min: 0
  - name: fk_account_exists
    type: referential
    from_table: transactions
    from_column: account_id
    to_table: accounts
    to_column: account_id